const menData = [{
    "id": 1,
    "imageURL": "/assets/MenWear/1.jpg",
    "category": "Menswear",
    "name": "Sporty Tee",
    "type": "Formal Shirt",
    "price": "299",
    "currency": "INR",
    "gender": "Men",
    "colour": "blue",
    "quantity": 3,
    "description": "A comfortable and stylish sporty t-shirt with moisture-wicking fabric."
},
{
    "id": 2,
    "imageURL": "/assets/MenWear/2.jpg",
    "category": "Menswear",
    "name": "ClassicFit",
    "type": "Casual Shirt",
    "price": "499",
    "currency": "INR",
    "gender": "Men",
    "colour": "Navy Blue",
    "quantity": 3,
    "description": "A classic fit dress shirt made from high-quality fabric, suitable for formal occasions."
},
{
    "id": 3,
    "imageURL": "/assets/MenWear/3.jpg",
    "category": "Menswear",
    "name": "511 Slim Fit",
    "type": "T-Shirt",
    "price": "59.50",
    "currency": "INR",
    "gender": "Men",
    "colour": "Mulity colours",
    "quantity": 1,
    "description": "Slim fit jeans with a modern look, perfect for casual outings."
},
{
    "id": 4,
    "imageURL": "/assets/MenWear/4.jpg",
    "category": "Menswear",
    "name": "Signature Polo",
    "type": "T-Shirt",
    "price": "690",
    "currency": "INR",
    "gender": "Men",
    "quantity": 3,
    "colour": "Black",
    "description": "A classic polo shirt with the iconic Ralph Lauren logo, ideal for a refined casual look."
},
{
    "id": 5,
    "imageURL": "/assets/MenWear/5.jpg",
    "category": "Menswear",
    "name": "Apex Bionic",
    "type": "Jacket",
    "price": "1299",
    "currency": "INR",
    "gender": "Men",
    "quantity": 0,
    "colour": "Green",
    "description": "A versatile softshell jacket designed for outdoor activities and everyday wear."
},
{
    "id": 6,
    "imageURL": "/assets/MenWear/6.jpg",
    "category": "Menswear",
    "name": "Tech Mesh Shorts",
    "type": "Hoodies",
    "price": "349",
    "currency": "INR",
    "gender": "Men",
    "quantity": 3,
    "colour": "White",
    "description": "Lightweight and breathable mesh shorts for workouts and active lifestyles."
},
{
    "id": 7,
    "imageURL": "/assets/MenWear/7.jpg",
    "category": "Menswear",
    "name": "Crewneck Sweater",
    "type": "Jacket",
    "price": "790",
    "currency": "INR",
    "gender": "Men",
    "quantity": 0,
    "colour": "Blue",
    "description": "A classic crewneck sweater made from soft and comfortable materials."
},
{
    "id": 8,
    "imageURL": "/assets/MenWear/8.jpg",
    "category": "Menswear",
    "name": "ModernFit Suit",
    "type": "Sweat Shirt",
    "price": "499",
    "currency": "INR",
    "gender": "Men",
    "quantity": 1,
    "colour": "Black",
    "description": "A modern-fit suit crafted with attention to detail, perfect for formal occasions."
},
{
    "id": 9,
    "imageURL": "/assets/MenWear/9.jpg",
    "category": "Menswear",
    "name": "Essentials Hoodie",
    "type": "Hoodies",
    "price": "449",
    "currency": "INR",
    "gender": "Men",
    "quantity": 6,
    "colour": "Oliv Green",
    "description": "A comfortable and stylish hoodie with the Adidas logo, suitable for everyday wear."
},
{
    "id": 10,
    "imageURL": "/assets/MenWear/10.jpg",
    "category": "Menswear",
    "name": "Alpha Khaki",
    "type": "Sweat Shirt",
    "price": "399",
    "currency": "INR",
    "gender": "Men",
    "quantity": 2,
    "colour": "Black",
    "description": "Versatile chino pants with a modern slim fit, suitable for casual and semi-formal occasions."
},
{
    "id": 11,
    "imageURL": "/assets/MenWear/11.jpg",
    "category": "Menswear",
    "name": "Endurance+ Swim Trunks",
    "type": "Sweat Shirt",
    "price": "295",
    "currency": "INR",
    "gender": "Men",
    "quantity": 7,
    "colour": "Black",
    "description": "Durable and comfortable swim trunks designed for performance and comfort in the water."
},
{
    "id": 12,
    "imageURL": "/assets/MenWear/12.jpg",
    "category": "Menswear",
    "name": "Classic Blazer",
    "type": "Blazer",
    "price": "1899",
    "currency": "INR",
    "gender": "Men",
    "quantity": 6,
    "colour": "Black",
    "description": "A timeless classic blazer suitable for both professional and smart-casual looks."
},
{
    "id": 13,
    "imageURL": "/assets/MenWear/black-polo-men.png",
    "name": "Black Polo",
    "type": "Polo",
    "price": 250,
    "currency": "INR",
    "colour": "Black",
    "gender": "Men",
    "quantity": 3,
    "description": "A timeless classic blazer suitable for both professional and smart-casual looks."
},
{
    "id": 14,
    "imageURL": "/assets/MenWear/black-hoodie-men.png",
    "name": "Black Hoodie",
    "type": "Hoodie",
    "price": 500,
    "currency": "INR",
    "colour": "Black",
    "gender": "Men",
    "quantity": 2,
    "description": "A comfortable and stylish sporty t-shirt with moisture-wicking fabric."
},
{
    "id": 15,
    "imageURL": "/assets/MenWear/green-polo-men.png",
    "name": "Green Polo",
    "type": "Polo",
    "price": 250,
    "currency": "INR",
    "colour": "Green",
    "gender": "Men",
    "quantity": 1,
    "description": "A classic fit dress shirt made from high-quality fabric, suitable for formal occasions."
},
{
    "id": 16,
    "imageURL": "/assets/MenWear/blue-round-men.png",
    "name": "Blue Round",
    "type": "Basic",
    "price": 300,
    "currency": "INR",
    "colour": "Blue",
    "gender": "Men",
    "quantity": 2,
    "description": "Slim fit jeans with a modern look, perfect for casual outings."
},
{
    "id": 17,
    "imageURL": "/assets/MenWear/grey-round-men.png",
    "name": "Grey Round",
    "type": "Basic",
    "price": 300,
    "currency": "INR",
    "colour": "Grey",
    "gender": "Men",
    "quantity": 1,
    "description": "A classic polo shirt with the iconic Ralph Lauren logo, ideal for a refined casual look."
},
{
    "id": 18,
    "imageURL": "/assets/MenWear/black-round-men.png",
    "name": "Black Round",
    "type": "Basic",
    "price": 300,
    "currency": "INR",
    "colour": "Black",
    "gender": "Men",
    "quantity": 7,
    "description": "A versatile softshell jacket designed for outdoor activities and everyday wear."
},
{
    "id": 19,
    "imageURL": "/assets/MenWear/purple-round-men.png",
    "name": "Purple Round",
    "type": "Basic",
    "price": 300,
    "currency": "INR",
    "colour": "Purple",
    "gender": "Men",
    "quantity": 1,
    "description": "Lightweight and breathable mesh shorts for workouts and active lifestyles."
},
{
    "id": 20,
    "imageURL": "/assets/MenWear/white-round-men.png",
    "name": "White Round",
    "type": "Basic",
    "price": 300,
    "currency": "INR",
    "colour": "White",
    "gender": "Men",
    "quantity": 2,
    "description": "A classic crewneck sweater made from soft and comfortable materials."
},
{
    "id": 21,
    "imageURL": "/assets/MenWear/red-polo-men.png",
    "name": "Red Polo",
    "type": "Polo",
    "price": 250,
    "currency": "INR",
    "colour": "Red",
    "gender": "Men",
    "quantity": 2,
    "description": "A modern-fit suit crafted with attention to detail, perfect for formal occasions."
},
{
    "id": 22,
    "imageURL": "/assets/MenWear/blue-hoodie-men.png",
    "name": "Blue Hoodie",
    "type": "Hoodie",
    "price": 500,
    "currency": "INR",
    "colour": "Blue",
    "gender": "Men",
    "quantity": 0,
    "description": "A comfortable and stylish hoodie with the Adidas logo, suitable for everyday wear."
},
{
    "id": 23,
    "imageURL": "/assets/MenWear/grey-hoodie-men.png",
    "name": "Grey Hoodie",
    "type": "Hoodie",
    "price": 500,
    "currency": "INR",
    "colour": "Grey",
    "gender": "Men",
    "quantity": 2,
    "description": "Versatile chino pants with a modern slim fit, suitable for casual and semi-formal occasions."
},
{
    "id": 24,
    "imageURL": "/assets/MenWear/grey-polo-men.png",
    "name": "Grey Polo",
    "type": "Polo",
    "price": 300,
    "currency": "INR",
    "colour": "Grey",
    "gender": "Men",
    "quantity": 3,
    "description": "Durable and comfortable swim trunks designed for performance and comfort in the water."
},
{
    "id": 25,
    "imageURL": "/assets/MenWear/red-hoodie-men.png",
    "name": "Red Hoodie",
    "type": "Hoodie",
    "price": 300,
    "currency": "INR",
    "colour": "Red",
    "gender": "Men",
    "quantity": 0,
    "description": "A timeless classic blazer suitable for both professional and smart-casual looks."
},
{
    "id": 26,
    "imageURL": "/assets/MenWear/white-polo-men.png",
    "name": "White Polo",
    "type": "Polo",
    "price": 300,
    "currency": "INR",
    "colour": "White",
    "gender": "Men",
    "quantity": 1,
    "description": "A timeless classic blazer suitable for both professional and smart-casual looks."
},
{
    "id": 27,
    "imageURL": "/assets/MenWear/grey-round-men.png",
    "name": "Grey Round",
    "type": "Basic",
    "price": 300,
    "currency": "INR",
    "colour": "Grey",
    "gender": "Men",
    "quantity": 0,
    "description": "A classic fit dress shirt made from high-quality fabric, suitable for formal occasions."
},
]

export default menData;