export const mobileData = [{

    "id": 1,
    "name": "OnePlus Nord CE 3 Lite 5G",
    "imageURL": "/assets/NewMobile/1.png",
    "brand": "One Plus",
    "price": 12999,
    "ram": "8 GB RAM | 256 GB ROM",
    "colour": "Black",
    "battery": "5000 mAh Battery",
    "camera": "108MP Rear Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 2,
    "name": "OPPO A78 5G (Glowing Blue, 128 GB)",
    "imageURL": "/assets/NewMobile/2.jpg",
    "brand": "Oppo",
    "price": 19006,
    "ram": "8 GB RAM | 128 GB ROM",
    "colour": "Glowing Blue",
    "battery": "5000 mAh Battery",
    "camera": "50MP + 2MP | 8MP Front Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 3,
    "name": "OnePlus Nord 4 5G (Oasis Green, 256 GB) ",
    "imageURL": "/assets/NewMobile/3.jpg",
    "brand": "One Plus",
    "price": 29977,
    "ram": "8 GB RAM | 256 GB ROM",
    "colour": "Oasis Green",
    "battery": "5500 mAh Battery",
    "camera": "50MP Rear Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 4,
    "name": "SAMSUNG GALAXY M13 5G",
    "imageURL": "/assets/NewMobile/4.jpg",
    "brand": "Samsung",
    "price": 19625,
    "ram": "6 GB RAM | 128 GB ROM",
    "colour": "Stardust Brown",
    "battery": "5000 mAh Battery",
    "camera": "50MP Rear Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 5,
    "name": "vivo Y16",
    "imageURL": "/assets/NewMobile/5.jpg",
    "brand": "Vivo",
    "price": 9988,
    "ram": "4 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
    "colour": "Drizzling Gold",
    "battery": "5000 mAh Lithium Battery",
    "camera": "13MP + 2MP | 5MP Front Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 6,
    "name": "REDMI Note 11S (Polar White, 128 GB)",
    "imageURL": "/assets/NewMobile/6.jpg",
    "brand": "Redmi",
    "price": 19499,
    "ram": "6 GB RAM | 128 GB ROM",
    "colour": "Polar White",
    "battery": "5000 mAh Battery",
    "camera": "108MP Rear Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 7,
    "name": "Tecno Spark 10 Pro (Pearl White, 128 GB)",
    "imageURL": "/assets/NewMobile/7.jpg",
    "brand": "Tecno",
    "price": 19449,
    "ram": "8 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
    "colour": "Pearl White",
    "battery": "5000 mAh Battery",
    "camera": "50MP Rear Camera | 32MP Front Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 8,
    "name": "KARBONN Jio Bharat K1",
    "imageURL": "/assets/NewMobile/8.jpg",
    "brand": "Karbon",
    "price": 779,
   "ram": "32 MB RAM | 32 MB MB ROM",
    "colour": "White & Red",
    "battery": "1000 mAh Battery",
    "camera": "1.3MP Rear Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 9,
    "name": "vivo V25 5G (Sunrise Gold, 128 GB)",
    "imageURL": "/assets/NewMobile/9.jpg",
    "brand": "Vivo",
    "price": 29999,
    "ram": "8 GB RAM | 128 GB ROM",
    "colour": "Sunrise Gold",
    "battery": "4500 mAh Lithium Battery",
    "camera": "64MP + 8MP + 2MP | 50MP Front Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 10,
    "name": "vivo V27 5G (Magic Blue, 128 GB) ",
    "imageURL": "/assets/NewMobile/10.jpg",
    "brand": "Vivo",
    "price": 30999,
    "ram": "8 GB RAM | 128 GB ROM",
    "colour": "Magic Blue,",
    "battery": "4600 mAh Battery",
    "camera": "50MP (OIS) + 8MP + 2MP | 50MP Front Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 11,
    "name": "OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)",
    "imageURL": "/assets/NewMobile/11.jpg",
    "brand": "One Plus",
    "price": 19999,
    "ram": "8 GB RAM | 128 GB ROM",
    "colour": "Bahama Blue",
    "battery": "4500 mAh Battery",
    "camera": "64MP Rear Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
},
{
    "id": 12,
    "name": "OPPO Reno10 Pro 5G (Silvery Grey, 256 GB) ",
    "imageURL": "/assets/NewMobile/12.jpg",
    "brand": "Oppo",
    "price": 39999,
    "ram": "12 GB RAM | 256 GB ROM",
    "colour": "Silvery Grey",
    "battery": "4600 mAh Battery",
    "camera": "50MP + 32MP + 8MP | 32MP Front Camera",
    "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}
]