const womenData = [
    {
        "id": 1,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/blue-polo-women.png",
        "name": "Blue Polo",
        "type": "Polo",
        "price": 350,
        "currency": "INR",
        "color": "Blue",
        "gender": "Women",
        "quantity": 3,
        "description": "A comfortable and stylish sporty t-shirt with moisture-wicking fabric."
    },
    {
        "id": 2,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/pink-polo-women.png",
        "name": "Pink Polo",
        "type": "Polo",
        "price": 350,
        "currency": "INR",
        "color": "Pink",
        "gender": "Women",
        "quantity": 6,
        "description": "A classic fit dress shirt made from high-quality fabric, suitable for formal occasions."
    },
    {
        "id": 3,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/green-polo-women.png",
        "name": "Green Polo",
        "type": "Polo",
        "price": 350,
        "currency": "INR",
        "color": "Green",
        "gender": "Women",
        "quantity": 1,
        "description": "Slim fit jeans with a modern look, perfect for casual outings."
    },
    {
        "id": 4,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/blue-hoodie-women.png",
        "name": "Blue Hoodie",
        "type": "Hoodie",
        "price": 500,
        "currency": "INR",
        "color": "Blue",
        "gender": "Women",
        "quantity": 2,
        "description": "A classic polo shirt with the iconic Ralph Lauren logo, ideal for a refined casual look."
    },
    {
        "id": 5,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/black-hoodie-women.png",
        "name": "Black Hoodie",
        "type": "Hoodie",
        "price": 500,
        "currency": "INR",
        "color": "Black",
        "gender": "Women",
        "quantity": 5,
        "description": "A versatile softshell jacket designed for outdoor activities and everyday wear."
    },
    {
        "id": 6,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/red-round-women.png",
        "name": "Red Round",
        "type": "Round Neck",
        "price": 300,
        "currency": "INR",
        "color": "Red",
        "gender": "Women",
        "quantity": 2,
        "description": "Lightweight and breathable mesh shorts for workouts and active lifestyles."
    },
    {
        "id": 7,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/purple-hoodie-women.png",
        "name": "Purple Hoodie",
        "type": "Hoodie",
        "price": 500,
        "currency": "INR",
        "color": "Purple",
        "gender": "Women",
        "quantity": 3,
        "description": "A classic crewneck sweater made from soft and comfortable materials."
    },
    {
        "id": 8,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/grey-round-women.png",
        "name": "Grey Round",
        "type": "Round Neck",
        "price": 300,
        "currency": "INR",
        "color": "Grey",
        "gender": "Women",
        "quantity": 1,
        "description": "A modern-fit suit crafted with attention to detail, perfect for formal occasions."
    },
    {
        "id": 9,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/white-round-women.png",
        "name": "White Round",
        "type": "Round Neck",
        "price": 300,
        "currency": "INR",
        "color": "White",
        "gender": "Women",
        "quantity": 0,
        "description": "A comfortable and stylish hoodie with the Adidas logo, suitable for everyday wear."
    },
    {
        "id": 10,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/blue-round-women.png",
        "name": "Blue Round",
        "type": "Round Neck",
        "price": 300,
        "currency": "INR",
        "color": "Blue",
        "gender": "Women",
        "quantity": 3,
        "description": "Versatile chino pants with a modern slim fit, suitable for casual and semi-formal occasions."
    },
    {
        "id": 11,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/yellow-hoodie-women.png",
        "name": "Yellow Hoodie",
        "type": "Hoodie",
        "price": 500,
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 1,
        "description": "Durable and comfortable swim trunks designed for performance and comfort in the water."
    },
    {
        "id": 12,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/white-polo-women.png",
        "name": "White Polo",
        "type": "Polo",
        "price": 350,
        "currency": "INR",
        "color": "White",
        "gender": "Women",
        "quantity": 4,
        "description": "A timeless classic blazer suitable for both professional and smart-casual looks."
    },
    {
        "id": 13,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/white-hoodie-women.png",
        "name": "White Hoodie",
        "type": "Hoodie",
        "price": 500,
        "currency": "INR",
        "color": "White",
        "gender": "Women",
        "quantity": 3,
        "description": "A timeless classic blazer suitable for both professional and smart-casual looks."
    },
    {
        "id": 14,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/black-round-women.png",
        "name": "Black Round",
        "type": "Round Neck",
        "price": 300,
        "currency": "INR",
        "color": "Black",
        "gender": "Women",
        "quantity": 0,
        "description": "A comfortable and stylish sporty t-shirt with moisture-wicking fabric."

    },
    {
        "id": 15,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/black-polo-women.png",
        "name": "Black Polo",
        "type": "Polo",
        "price": 300,
        "currency": "INR",
        "color": "Black",
        "gender": "Women",
        "quantity": 4,
        "description": "A classic fit dress shirt made from high-quality fabric, suitable for formal occasions."
    },
    {
        "id": 16,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/1.jpg",
        "type": "Dress",
        "name": "Flowy Maxi",
        "price": "799",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 1,
        "description": "A flowy maxi dress with floral patterns, perfect for summer occasions."
    },
    {
        "id": 17,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/2.jpg",
        "type": "Blouse",
        "name": "Classic Silk",
        "price": "499",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 1,
        "description": "A classic silk blouse suitable for professional and casual settings."
    },
    {
        "id": 18,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/3.jpg",
        "type": "Jeans",
        "name": "501 Skinny",
        "price": "895",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 1,
        "description": "Skinny fit jeans with a classic 5-pocket design, perfect for everyday wear."
    },
    {
        "id": 19,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/4.jpg",
        "type": "Jumpsuit",
        "name": "Utility Jumpsuit",
        "price": "599",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 2,
        "description": "A utility-style jumpsuit with a modern and versatile look."
    },
    {
        "id": 20,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/5.jpg",
        "type": "Skirt",
        "name": "A-Line Mini",
        "price": "1399",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 1,
        "description": "A stylish A-line mini skirt with a retro touch, suitable for various occasions."
    },
    {
        "id": 21,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/6.jpg",
        "type": "Sweater",
        "name": "Cable Knit",
        "price": "499",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 1,
        "description": "A cozy cable knit sweater with a timeless design, perfect for chilly days."
    },
    {
        "id": 22,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/7.jpg",
        "type": "Blazer",
        "brand": "Mango",
        "name": "Tailored Blazer",
        "price": "7999",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 5,
        "description": "A tailored blazer with a chic silhouette, suitable for formal and casual looks."
    },
    {
        "id": 23,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/8.jpg",
        "type": "Leggings",
        "name": "Align Leggings",
        "price": "980",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 1,
        "description": "High-quality leggings with a buttery soft feel, ideal for yoga and workouts."
    },
    {
        "id": 24,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/8.jpg",
        "type": "Swimwear",
        "name": "Bikini Set",
        "price": "595",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 2,
        "description": "A stylish bikini set with vibrant patterns, perfect for beach days."
    },
    {
        "id": 25,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/10.jpg",
        "type": "Pants",
        "name": "High-Rise Skinny",
        "price": "499",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 7,
        "description": "High-rise skinny pants with a flattering fit, suitable for various occasions."
    },
    {
        "id": 26,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/11.jpg",
        "type": "Coat",
        "name": "Wool Blend Coat",
        "price": "2900",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 5,
        "description": "A stylish wool blend coat with a modern and elegant design, perfect for colder days."
    },
    {
        "id": 27,
        "category": "Woman Wear",
        "imageURL": "/assets/WomanWear/12.jpg",
        "type": "T-Shirt",
        "name": "Graphic Tee",
        "price": "2495",
        "currency": "INR",
        "color": "Yellow",
        "gender": "Women",
        "quantity": 3,
        "description": "A casual graphic tee with trendy prints, suitable for relaxed everyday outfits."
    }
]

export default womenData;